name: usecase-delivery-planning-agent
description: "AI-powered Usecase Delivery Planning Agent with React UI"

command:
  - gunicorn
  - server.app:app
  - -w
  - "2"
  - -k
  - uvicorn.workers.UvicornWorker
  - --bind
  - "0.0.0.0:8000"

env:
  - name: SERVING_ENDPOINT_NAME
    valueFrom:
      databricks:
        resource: serving-endpoint/usecase-planning-agent
